// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMDXCDQjKi4eYeY4cTIul5TP1WtqnYcjc',
    appId: '1:883729268140:android:e0b7672b28ef6c6365ce09',
    messagingSenderId: '883729268140',
    projectId: 'bus-location-tracker-b309f',
    storageBucket: 'bus-location-tracker-b309f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT-IOXeUDGNd5nPrQK8PDmu1UvS7h1VS4',
    appId: '1:883729268140:ios:79f99870b4ae968765ce09',
    messagingSenderId: '883729268140',
    projectId: 'bus-location-tracker-b309f',
    storageBucket: 'bus-location-tracker-b309f.firebasestorage.app',
    iosClientId: '883729268140-eucrbr75u80vt34bqkn39vcq2dpr4hcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.busLocationTracker',
  );
}
